mutation LoginOrCreateUser($username: String!) {
  loginOrCreateUser(data: { username: $username }) {
    token
    user {
      id
      username
      favourites {
        id
        name
        image
        species
        gender
        status
        origin {
          name
          dimension
        }
        episode {
          id
          name
          air_date
        }
      }
    }
  }
}
