query Characters($page: Int) {
  characters(page: $page) {
    info {
      pages
      next
      prev
    }
    results {
      id
      name
      image
      species
      gender
      status
      origin {
        name
        dimension
      }
    }
  }
}
