mutation AddFavourite($data: addFavouriteInput!) {
  addFavourite(data: $data) {
    id
    username
    favourites {
      id
      name
      image
      species
      gender
      status
      origin {
        name
        dimension
      }
      episode {
        id
        name
        air_date
      }
    }
  }
}

mutation RemoveFavourite($data: removeFavouriteInput!) {
  removeFavourite(data: $data) {
    id
    username
    favourites {
      id
      name
      image
      species
      gender
      status
      origin {
        name
        dimension
      }
      episode {
        id
        name
        air_date
      }
    }
  }
}

# fragment FavouriteDetail on Cha
