mutation AddFavourite($data: addFavouriteInput!) {
  addFavourite(data: $data) {
    ...UserDetail
  }
}

mutation RemoveFavourite($data: removeFavouriteInput!) {
  removeFavourite(data: $data) {
    ...UserDetail
  }
}

fragment UserDetail on User {
  id
  username
  favourites {
    ...FavouriteDetail
  }
}

fragment FavouriteDetail on Character {
  id
  name
  image
  species
  gender
  status
  origin {
    name
    dimension
  }
  episode {
    id
    name
    air_date
  }
}
